package cryptoutil

import (
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/hex"
	"testing"
)

func TestDerivePassphraseKeyCompatibility(t *testing.T) {
	key, err := derivePassphraseKey("password", []byte("0123456789abcdef"))
	if err != nil {
		t.Fatal(err)
	}
	// This vector was generated by the previous RFC 8018-compatible
	// implementation and protects backward compatibility of persisted blobs.
	if got, want := hex.EncodeToString(key), "996d7c90f74a4a169cf7adef42b06848f7d1bac3e568d1cc94d4f79be1ee0263"; got != want {
		t.Fatalf("derived key = %s, want %s", got, want)
	}
}

func TestSealWithPassphraseRoundTripAndTamperDetection(t *testing.T) {
	plaintext := []byte("private key material")
	sealed, err := SealWithPassphrase(plaintext, "strong-test-passphrase")
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(sealed, plaintext) {
		t.Fatal("sealed data contains plaintext")
	}

	opened, err := OpenWithPassphrase(sealed, "strong-test-passphrase")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(opened, plaintext) {
		t.Fatalf("opened = %q", opened)
	}

	tampered := append([]byte(nil), sealed...)
	tampered[len(tampered)-8] ^= 1
	if _, err := OpenWithPassphrase(tampered, "strong-test-passphrase"); err == nil {
		t.Fatal("tampered blob was accepted")
	}
	if _, err := OpenWithPassphrase(sealed, "wrong-passphrase"); err == nil {
		t.Fatal("wrong passphrase was accepted")
	}
}

func TestHashAndEd25519PEMHelpers(t *testing.T) {
	publicKey, privateKey, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	tagged := SHA256Tagged([]byte("document"))
	if len(tagged) != len("sha256:")+64 {
		t.Fatalf("tagged hash = %q", tagged)
	}
	if _, err := HashPublicKey(publicKey); err != nil {
		t.Fatal(err)
	}

	pemBytes, err := MarshalEd25519PrivateKeyPEM(privateKey)
	if err != nil {
		t.Fatal(err)
	}
	parsed, err := ParseEd25519PrivateKeyPEM(pemBytes)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(parsed, privateKey) {
		t.Fatal("private key PEM round trip mismatch")
	}

	secret := []byte("secret")
	ZeroBytes(secret)
	if !bytes.Equal(secret, make([]byte, len(secret))) {
		t.Fatal("ZeroBytes did not clear data")
	}
}
